src/mod.ts
This change adds the `runtime` property to hooks library. `runtime` formerly existed in the manifest authoring layer but has been removed in favor of it living in project configuration (i.e. slack.json). This is the more correct place for this to live, as it's project specific and not app-specific (see: https://github.com/slackapi/deno-slack-sdk/pull/15).
=> Adds runtime property formerly located in manifest

src/check-update.ts
No longer need to check for builder and runtime updates since those are controlled as variables in this repo.
=> Remove checking of builder and runtime SDKs when checking for updates.

src/deps.ts, src/dev_deps.ts, src/flags.ts, src/mod.ts, src/tests/flags_test.ts
Allows the CLI to pass in a flag `--sdk-unsafely-ignore-certificate-errors` to `get-hooks` to tell the SDK to pass the specific domain to Deno's `--unsafely-ignore-certificate-errors` flag in the `start` hook, so that it doesn't complain about SSL errors on numbered dev instances. 
Testing instructions:
* manually run the get-hooks hook with this new flag: `deno run -q --unstable --allow-read --allow-net <path to>/deno-slack-hooks/src/mod.ts --sdk-unsafely-ignore-certificate-errors=dev1234.slack.com`. Verify the start hook contains `--unsafely-ignore-certificate-errors=dev1234.slack.com`
=> [HERMES-2554] Support disabling Deno SSL certificate verification via flag

.gitignore, README.md, deno.jsonc, src/mod.ts
This updates the deno_slack_builder version used in the hooks to 0.0.12, which has changes that support Deno `v1.22.0` (accounting for `Deno.emit()` removal). I was also able to remove our inclusion of the `--unstable` flags in each of our hooks, as we're no longer using any unstable apis.
* We needed to add an allow-run flag to our build script now that it calls out to Deno.run when bundling.
* Also added a deno.jsonc w/ a test task to making running the tests/fmt/lint locally a bit easier.
* Updated the Readme to be version agnostic in it's example.
Update a project's `slack.json` to point to a local version of these hooks. Notice we can also drop the `--unstable` flag here as well.
```
{
"hooks": {
"get-hooks": "deno run -q --allow-read --allow-net …
```
=> Updated hooks for builder 0.0.12

src/libraries.ts
We need to make sure the git tags and the self-referential version in the code match, otherwise the response to the `get-hooks` hook will return older hook info.
Problem I just saw: right now if you use hooks v0.0.8 in a new deno-reverse-string app, and run `slack -v version` to trigger the `check-update` flow, because the self-referred hooks version is set to 0.0.6, but the git-tagged version of this repo is 0.0.8, the `check-update` flow will fail (because hooks v0.0.6 does not contain a `check-update` hook implementation).
=> Bumping hooks version to 0.0.9

src/create-trigger.ts, src/deps.ts, src/get_trigger.ts
@sopokuagyemang is working on adding a new hook to the CLI for trigger creation. While waiting on that, I have implemented this `get-trigger` hook that will accept a `json` file or a file with a default export, and log it to `stdout` for consumption.
You can either pull this down and run the script directly via
```bash
deno run --allow-read ./src/get-trigger.ts --source=your-trigger-file.json.
```
You can also run this directly by referencing the commit hash
```bash
deno run --allow-read https://raw.githubusercontent.com/slackapi/deno-slack-hooks/d9f93add46ccc39bda5aa8ad10a24c88524fcd6e/src/create-trigger.ts --source=your-trigger-file.ts
```
=> Adding get-trigger hook

.github/maintainers_guide.md, src/libraries.ts, src/version.ts
In prep for v0.0.11 release, bumping the version string of this library to 0.0.11, fixing up some incorrect references to GitHub Teams, and also bumping runtime and builder libs to latest version.
=> 0.0.11 release

src/check_update.ts, src/deps.ts, src/dev_deps.ts, src/install_update.ts, src/tests/check_update_test.ts, src/tests/install_update_test.ts, src/utilities.ts
This PR adds support for parsing `.jsonc` files (in addition to `.json`) that might be encountered when checking for and installing dependency updates. Also added support for `deno.*` configuration files.
**A special note because I'm not excessively type-checking here just for my sake:**
- Making use of Deno's standard library `parse` function created some.. interesting hoops to jump through. Specifically, the return value is a `JSONValue` which can be _almost_ anything but not quite. As such, its inclusion has required a lot of inconvenient checks to verify that the shape being dealt with is kosher. See all of those `isParsable`? Fun times.
After each of the following scenarios,  run `hermes update` and verify that you can see the updates, and, when subsequently auto-updating, that the …
=> Add support for .jsonc files during check-update and install-update

src/libraries.ts
This just updates the versions of the builder and the runtime that we use in this library
=> Bump versions of builder and runtime

src/check_update.ts, src/install_update.ts, src/tests/check_update_test.ts, src/tests/install_update_test.ts, src/utilities.ts
This PR makes several changes to `check_update`, `install_update` and the `getJSON` utility function to enable the raising, handling, and relaying of errors that occur when accessing dependency files.
https://user-images.githubusercontent.com/7788242/182486018-4f6661c0-ab4c-41e8-8c62-687f804730ac.mov
https://user-images.githubusercontent.com/7788242/182486057-d33a1c6f-c20b-4ad9-b05f-a7d854a14096.mov
https://user-images.githubusercontent.com/7788242/182487045-871fa707-7f33-4fcc-9d5c-2308cfb1929d.mov
After each of the following scenarios,  run `hermes update` and verify that you can see the expected output:
- **Happy Path**. Downgraded some dependencies in `slack.json` and `import_map.json`. Verify that no errors are surfaced.
- **Missing Files**. Rename your `import_map.json` to something …
=> Raise, handle, and relay errors that occur when accessing dependency files

README.md
This just adds some script details to the README in case anyone comes looking for more info.
=> Add script usage to the README

src/check_update.ts
This PR adjusts the `check-update` logic to return all dependency information, regardless of whether or not there is an update available. This is necessary for the `doctor` command to provide the user information about the dependencies in their project.
=> Return all dependencies during check-update

src/mod.ts
Updates the watch regex to watch any `.js` or `.ts` file changes instead just the manifest file. Not watching `.json` files atm as it would pick up changes in the `.slack` folder that occur on every update/deploy (so it would trigger itself indefinitely).
I tried to use a regex w/ a negative look-ahead, `/^(?!\.slack).*\.(ts|js|json)$/`, to filter out the `.slack` folder, but that syntax isn't available in GoLang, which the CLI that interprets this watch config uses.
In the future we'd like to have the CLI automatically filter out changes in the `.slack` folder, which would allow us to watch json files again w/o issue.
Update your `slack.json` file to use the hooks from this PR:
```json
{
"hooks": {
"get-hooks": "deno run -q --allow-read --allow-net …
```
=> watch all js/ts files

src/check_update.ts, src/tests/check_update_test.ts
This PR updates the `check-update` hook to pull version information directly from the `metadata.json` that's published at https://api.slack.com/slackcli/metadata.json.
=> Update check-update to pull from metadata.json

src/flags.ts, src/libraries.ts, src/mod.ts, src/tests/flags_test.ts
Hooks updates for https://github.com/slackapi/deno-slack-runtime/pull/39 and bumps the runtime version
=> [HERMES-4040] Support runtime 0.4.0

src/check_update.ts, src/install_update.ts, src/tests/check_update_test.ts
We shouldn't prompt the user to upgrade if they're on a newer version. This is being put in place now that we're going to have a suggested version rather than when we always just used latest.
Change your versions manually and then run the hook locally
```bash
deno run -q --config=deno.jsonc --allow-run --allow-read --allow-write --allow-net <your-local-path>/deno-slack-hooks/src/install_update.ts
```
=> Comparing semver to know if we need to update

src/mod.ts
Implement App manifest override proposal with environment variables
- Proposal: https://corp.quip.com/O1t1AuDG3HLk/App-Manifest-Overrides
- JIRA: https://jira.tinyspeck.com/browse/HERMES-4137
Related CLI PR:
- https://github.com/slackapi/slack-cli/pull/776
Related runtime PR: 
- https://github.com/slackapi/deno-slack-runtime/pull/40
=> Allow environment variables in hooks related to running locally or deploying to ROSI

src/libraries.ts
This pull request updates the Deno Slack Runtime to 0.5.1 ([release notes](https://github.com/slackapi/deno-slack-runtime/releases/tag/0.5.1)).
=> Update Deno Slack Runtime to 0.5.1

.github/maintainers_guide.md, .vscode/settings.json, deno.jsonc
This is related to the deno-slack-sdk [local environment changes](https://github.com/slackapi/deno-slack-sdk/pull/141)
This applies the same configurations for linting and formatting as the deno-slack-sdk.
RELEASE NOTE: This PR alone does not require a new release!
=> added lint and format guidelines

src/mod.ts
This was a user request asking enable Environment variables in trigger files, this PR adds this functionality. 
JIRA: HERMES-4830
testing steps:
1. add the following to your `slack.json` file in a test application
```json
"get-trigger":
"deno run -q --config=deno.jsonc --allow-read --allow-net --allow-env https://deno.land/x/deno_slack_hooks/get_trigger.ts"
```
2. Add something in a trigger file that uses environment variables ex: `Deno.env.get("NAME")`
3. execute a trigger update ex: `hermes trigger update --trigger-def triggers/<path to my trigger>.ts --trigger-id <my trigger ID>`
4. Everything should be successful
=> Allow env for get trigger hook

.gitignore, deno.jsonc
Small tweak to the coverage task, I think the output is much nicer and it also gives you a project-wide total (which the built-in deno CLI `deno coverage` tool does not):
=> Integrate a better CLI utility for generating code coverage reports.

deno.jsonc
#65 will move us from `Deno.run` to `Deno.Command` but in the meantime we need to disable this lint rule to prevent our CI/CD checks from failing
=> Temporarily exclude no-deprecated-deno-api lint rule

deno.jsonc, src/tests/get_trigger_test.ts
This PR aims to improve the stability of the tests by adding asynchronous expressions
=> [FIX] concurrency issue in tests

src/bundler/esbuild_bundler.ts
This PR introduces a patch that allows ebuild to bundle a wider range of npm specifiers note that this is not a full proof solution and that packages such as [axios](https://www.npmjs.com/package/axios) will bundle correctly but create runtime errors
1. create an app that uses an npm specifier example `dayjs` 
```ts
import dayjs from "npm:dayjs@1.11.10";
const test = dayjs("2018-08-08");
console.log(test.year());
```
2. run `slack deploy`
3. The app should bundle and run as expected
=> update the plateform to support more imports

.github/workflows/deno-ci.yml
Testing out this alpha GitHub Action we are working on
=> Give health score a shot

.github/workflows/deno-ci.yml
also explicitly has check-writing permissions.
=> Split out health score as separate job that runs after test

.github/workflows/deno-cd.yml, .github/workflows/deno-ci.yml
This PR uses the wonderful [`zizmor`](https://github.com/zizmorcore/zizmor) tool to audit our own workflows and [`pinact`](https://github.com/suzuki-shunsuke/pinact) for pinned versioning 👾 
A similar audit can be performed with the `zizmor` tool:
```sh
$ zizmor .
...
No findings to report. Good job! (2 suppressed)
```
> The suppressed findings are expected permission blocks at the top-level of a workflow, but we set this for each job.
=> ci: pin actions workflow step hashes and use minimum permissions

src/check_update.ts, src/install_update.ts, src/tests/check_update_test.ts, src/tests/install_update_test.ts
This PR adds `deno.json` and `deno.jsonc` to the list of files containing `imports` with dependencies to update for support of recent sample changes 🤖 ✨ 
Confirm the `doctor` command finds these dependencies:
```sh
$ slack create asdf -t slack-samples/deno-starter-template
$ cd asdf
$ vim .slack/hooks.json
{
"hooks": {
"get-hooks": "deno run -q --allow-read --allow-net https://deno.land/x/deno_slack_hooks@1.3.2/mod.ts",
"check-update": "deno run -q --allow-read --allow-net /path/to/deno-slack-hooks/src/check_update.ts",
"install-update": "deno run -q --config=deno.jsonc --allow-run --allow-read --allow-write --allow-net /path/to/deno-slack-hooks/src/install_update.ts"
}
}
$ slack doctor
$ vim deno.jsonc
{
"...": {},
"imports": {
"@std/assert": "jsr:@std/assert@^1.0.13",
"@std/testing": …
```
=> fix: check updates for known deps imported in deno configs & .slack/hooks
