slackapi/deno-slack-hooks

src/mod.ts
Bump the versions of the builder and runtime
=> Bump the versions of the builder and runtime

src/mod.ts
=> Bumping builder to 0.0.10

.github/CONTRIBUTING.md, .github/maintainers_guide.md, .github/workflows/deno.yml, README.md, deno.jsonc
…, add lint and fmt config to deno.jsonc, update contributing and maintainer guides.
=> Update README, add testing instructions

src/libraries.ts, src/version.ts
Update libraries.ts to reference to latest dependencies for release (June 10th, 2022)
=> Update libraries.ts to reference to latest dependencies

.vscode/settings.json
Remove Deno unstable vscode setting
=> Remove unstable from vscode settings

src/version.ts
Release version `0.1.0` of this library
=> 0.1.0 release branch

src/version.ts
Release version `0.1.1` of this library
=> 0.1.1 release branch

src/libraries.ts
Bumps `deno-slack-runtime` to `0.2.0`
=> updating deno-slack-runtime to 0.2.0

src/version.ts
Bump `version` to release 0.3.0
=> bumping to 0.3.0

src/libraries.ts
Updates the included version of `deno-slack-runtime` to `0.2.1` to include a couple bug-fixes.
=> updating deno_slack_runtime to 0.2.1

src/version.ts
Creating PR to bump the version number as per the releasing guide
* Update check-update to pull from metadata.json by @misscoded in https://github.com/slackapi/deno-slack-hooks/pull/41
* [HERMES-4040] Support runtime 0.4.0 by @mcodik in https://github.com/slackapi/deno-slack-hooks/pull/40
=> Update version to 0.6.0

src/version.ts
Creating PR to bump the version number as per the releasing guide
Changes:
[Comparing semver to know if we need to update](https://github.com/slackapi/deno-slack-hooks/pull/43)
=> Update version to 0.7.0

src/libraries.ts
=> Update deno-slack-runtime version to 0.5.0

src/version.ts
=> Update version.ts to 0.8.0

src/libraries.ts
=> Update builder version

src/libraries.ts, src/version.ts
Update builder version to `0.2.1` and bump hooks version for release
=> Update builder version to `0.2.1` and bump hooks version for release

src/version.ts
=> Bump version

src/libraries.ts, src/version.ts
Bump library versions (including this one)
=> Version bump

src/version.ts
Major version bump for release
=> Major version bump for release

.github/maintainers_guide.md, README.md, src/tests/fixtures/functions/test_function_file.ts, src/tests/fixtures/functions/test_function_no_export_file.ts, src/tests/fixtures/functions/test_function_not_function_file.ts, src/tests/mod_test.ts
This PR aims to update the project to follow the new Slack Term Glossary, this mainly affect documentation and comments, variable names were left unchanged to avoid breaking changes.
=> Update with glossary terms

src/version.ts
Mainly includes deno-slack-runtime 1.1.0, which adds support for the `SLACK_DEBUG` env var.
=> Bumping version for release 1.1.0

README.md, src/check_update.ts
This PR changes the displayed link to the changelog when updates are available to avoid redirects!
=> Update redirected link to the changelog

src/version.ts
Releasing new version of package
=> chore: release 1.3.1

.github/PULL_REQUEST_TEMPLATE.md
Small housekeeping PR to hopefully help a little with maintainer sanity 🤪
=> style: remove extra space from pull request template

src/version.ts
=> chore: release 1.3.2

.github/workflows/deno-cd.yml, .github/workflows/deno-ci.yml, deno.jsonc, src/README.md, src/build.ts, src/check_update.ts, src/dev_deps.ts, src/doctor.ts, src/get_manifest.ts, src/get_trigger.ts, src/install_update.ts, src/tests/check_update_test.ts, src/tests/doctor_test.ts, src/tests/install_update_test.ts, src/utilities.ts
These changes update the projects source code and CI flow to support Deno 2, along with some minor improvements
=> fix: support deno version 2.x

src/libraries.ts, src/version.ts
Bump deno slack runtime version to [1.1.3](https://deno.land/x/deno_slack_runtime@1.1.3) and release a new version
=> chore: release 1.4.0
